const studentsData = [{
    id: 1,
    name: "John Doe",
    age: 20,
    class: "10th Grade",
    gender: "Male",
    dob: "2003-05-15",
},
{
    id: 2,
    name: "Jane Smith",
    age: 22,
    class: "12th Grade",
    gender: "Female",
    dob: "2003-05-15",
},
{
    id: 3,
    name: "Sam Wilson",
    age: 19,
    class: "9th Grade",
    gender: "Male",
    dob: "2003-05-15",
},
{
    id: 4,
    name: "Sara Connor",
    age: 21,
    class: "11th Grade",
    gender: "Female",
    dob: "2003-05-15",
},
{
    id: 5,
    name: "Peter Parker",
    age: 20,
    class: "10th Grade",
    gender: "Male",
    dob: "2003-05-15",
},
{
    id: 6,
    name: "Bruce Wayne",
    age: 22,
    class: "12th Grade",
    gender: "Male",
    dob: "2003-05-15",
},
{
    id: 7,
    name: "Clark Kent",
    age: 19,
    class: "9th Grade",
    gender: "Male",
    dob: "2003-05-15",
},
{
    id: 8,
    name: "Diana Prince",
    age: 21,
    class: "11th Grade",
    gender: "Female",
    dob: "2003-05-15",
},
{
    id: 9,
    name: "Tony Stark",
    age: 20,
    class: "10th Grade",
    gender: "Male",
    dob: "2003-05-15",
},
{
    id: 10,
    name: "Natasha Romanoff",
    age: 22,
    class: "12th Grade",
    gender: "Female",
    dob: "2003-05-15",
},
{
    id: 11,
    name: "Wade Wilson",
    age: 19,
    class: "9th Grade",
    gender: "Male",
    dob: "2003-05-15",
},
{
    id: 12,
    name: "Harley Quinn",
    age: 21,
    class: "11th Grade",
    gender: "Female",
    dob: "2003-05-15",
},
{
    id: 13,
    name: "Stephen Strange",
    age: 20,
    class: "10th Grade",
    gender: "Male",
    dob: "2003-05-15",
}]
const vaccinesData = [
    {
        id: 1,
        name: "COVID-19 Vaccine",
        classes: "10, 11, 12",
        sceduledDate: "2023-01-15",
        availableDoses: 1,
        active: true,
    },
    {
        id: 2,
        name: "Flu Vaccine",
        classes: "9, 10, 11, 12",
        sceduledDate: "2023-02-20",
        availableDoses: 2,
        active: true,
    },
    {
        id: 3,
        name: "Hepatitis B Vaccine",
        classes: "10, 11, 12",
        sceduledDate: "2023-03-25",
        availableDoses: 1,
        active: true,
    },
    {
        id: 4,
        name: "Measles Vaccine",
        classes: "9, 10, 11, 12",
        sceduledDate: "2023-04-30",
        availableDoses: 2,
        active: true,
    },
    {
        id: 5,
        name: "Tetanus Vaccine",
        classes: "10, 11, 12",
        sceduledDate: "2023-05-15",
        availableDoses: 1,
        active: false,
    },
    {
        id: 6,
        name: "Mumps Vaccine",
        classes: "9, 10, 11, 12",
        sceduledDate: "2023-06-20",
        availableDoses: 2,
        active: true,
    },
    {
        id: 7,
        name: "Rubella Vaccine",
        classes: "10, 11, 12",
        sceduledDate: "2023-07-25",
        availableDoses: 1,
        active: true,
    },
    {
        id: 8,
        name: "Chickenpox Vaccine",
        classes: "9, 10, 11, 12",
        sceduledDate: "2023-08-30",
        availableDoses: 2,
        active: false,
    },
    {
        id: 9,
        name: "Polio Vaccine",
        classes: "10, 11, 12",
        sceduledDate: "2023-09-15",
        availableDoses: 1,
        active: true,
    },
    {
        id: 10,
        name: "HPV Vaccine",
        classes: "9, 10, 11, 12",
        sceduledDate: "2023-10-20",
        availableDoses: 2,
        active: true,
    },
    {
        id: 11,
        name: "COVID-19 Booster Vaccine",
        classes: "10, 11, 12",
        sceduledDate: "2023-11-25",
        availableDoses: 1,
        active: true,
    },
    {
        id: 12,
        name: "Flu Booster Vaccine",
        classes: "9, 10, 11, 12",
        sceduledDate: "2023-12-30",
        availableDoses: 2,
        active: false,
    },
    {
        id: 13,
        name: "Hepatitis A Vaccine",
        classes: "10, 11, 12",
        sceduledDate: "2024-01-15",
        availableDoses: 1,
        active: true,
    },
    {
        id: 14,
        name: "Meningococcal Vaccine",
        classes: "9, 10, 11, 12",
        sceduledDate: "2024-02-20",
        availableDoses: 2,
        active: true,
    },
    {
        id: 15,
        name: "Shingles Vaccine",
        classes: "10, 11, 12",
        sceduledDate: "2024-03-25",
        availableDoses: 1,
        active: true,
    },
]

export {
    studentsData,
    vaccinesData
}